### ISSUE TITLE
Add context with indentation

### ISSUE THREAD

**Issue by math2001** [math2001/YAMLKeymap#15]
Something like this:

```yaml
- with_contexts:
  - context_names:
    - context1
    - context2
  
  - keys: ..
    # these keybindings would have the contexts
```
